/* ── Timing Engine — Canonical Tags ── */

export const IRON = "IRON";
export const DIVALENT_CATION = "DIVALENT_CATION";
export const THYROID_HORMONE = "THYROID_HORMONE";
export const BISPHOSPHONATE = "BISPHOSPHONATE";
export const TETRACYCLINE = "TETRACYCLINE";
export const FLUOROQUINOLONE = "FLUOROQUINOLONE";
export const INTEGRASE_INHIBITOR = "INTEGRASE_INHIBITOR";
export const ACID_REDUCER = "ACID_REDUCER";
export const BINDING_AGENT = "BINDING_AGENT";
export const STIMULANT = "STIMULANT";
export const NARROW_TW = "NARROW_TW";
export const WITH_FOOD_RECOMMENDED = "WITH_FOOD_RECOMMENDED";
export const AVOID_LATE = "AVOID_LATE";
export const HIGH_FIBER = "HIGH_FIBER";
export const CAFFEINE = "CAFFEINE";
export const HIGH_PROTEIN_MEAL = "HIGH_PROTEIN_MEAL";

export const ALL_TAGS = [
  IRON, DIVALENT_CATION, THYROID_HORMONE, BISPHOSPHONATE,
  TETRACYCLINE, FLUOROQUINOLONE, INTEGRASE_INHIBITOR,
  ACID_REDUCER, BINDING_AGENT, STIMULANT, NARROW_TW,
  WITH_FOOD_RECOMMENDED, AVOID_LATE, HIGH_FIBER, CAFFEINE,
  HIGH_PROTEIN_MEAL,
] as const;
